import PDFDocument from "pdfkit";
import cloudinary from "cloudinary";
import { ICertificate } from "../models/certificate.model";
import Course from "../models/course.model";
import User from "../models/user.model";

const uploadPdfToCloudinary = (buffer: Buffer, publicId: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.v2.uploader.upload_stream(
      {
        resource_type: "raw",
        folder: "certificates",
        public_id: publicId,
        format: "pdf",
      },
      (error, result) => {
        if (error || !result) return reject(error);
        resolve(result.secure_url);
      }
    );
    stream.end(buffer);
  });
};

interface GenerateCertificateOptions {
  certificate: ICertificate;
}

export const generateCertificatePdf = async ({
  certificate,
}: GenerateCertificateOptions): Promise<string> => {
  const user = await User.findById(certificate.userId);
  const course = await Course.findById(certificate.courseId);
  if (!user || !course) {
    throw new Error("User or course not found for certificate generation");
  }

  const doc = new PDFDocument({
    size: "A4",
    layout: "landscape",
    margin: 50,
  });

  const chunks: Buffer[] = [];

  return new Promise<string>((resolve, reject) => {
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        const pdfUrl = await uploadPdfToCloudinary(pdfBuffer, certificate.certificateId);
        resolve(pdfUrl);
      } catch (err) {
        reject(err);
      }
    });

    doc.rect(0, 0, doc.page.width, doc.page.height).fill("#f5f5f5");

    doc
      .fontSize(32)
      .fillColor("#222")
      .font("Helvetica-Bold")
      .text("Certificate of Completion", {
        align: "center",
        underline: true,
      });

    doc.moveDown(2);

    doc
      .fontSize(18)
      .fillColor("#444")
      .font("Helvetica")
      .text("This certifies that", { align: "center" });

    doc.moveDown(1);

    doc
      .fontSize(28)
      .fillColor("#000")
      .font("Helvetica-Bold")
      .text(user.name || user.email, {
        align: "center",
      });

    doc.moveDown(1.5);

    doc
      .fontSize(18)
      .fillColor("#444")
      .font("Helvetica")
      .text("has successfully completed the course", {
        align: "center",
      });

    doc.moveDown(1);

    doc
      .fontSize(24)
      .fillColor("#000")
      .font("Helvetica-Bold")
      .text(course.name, {
        align: "center",
      });

    doc.moveDown(2);

    const issuedDate = certificate.issuedAt.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    doc
      .fontSize(12)
      .fillColor("#555")
      .font("Helvetica")
      .text(`Issued on: ${issuedDate}`, {
        align: "center",
      });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("#777")
      .text(`Certificate ID: ${certificate.certificateId}`, {
        align: "center",
      });

    doc.moveDown(3);

    const centerX = doc.page.width / 2;
    doc
      .moveTo(centerX - 100, doc.y)
      .lineTo(centerX + 100, doc.y)
      .strokeColor("#555")
      .stroke();

    doc.moveDown(0.3);

    doc
      .fontSize(12)
      .fillColor("#333")
      .text("Authorized Signature", centerX - 60, doc.y, {
        align: "left",
      });

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#999")
      .text("Generated by AO LMS • Powered by Node.js & MongoDB", {
        align: "center",
      });

    doc.end();
  });
};
